kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: dockerhub_login
    password:
      from_secret: dockerhub_password
    repo: zethis/docker-xymon
    tags: latest
trigger:
  event:
  - cron
  - tag
